#Home task: pandas

###Question 1

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
try:
  Energy = pd.read_excel("/content/Energy Indicators.xls", header = 16, skiprows = [17])
  print("Successfully loaded data")
except FileNotFoundError:
  print("File not found")
Energy.head()

Successfully loaded data

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Energy Supply,Energy Supply per capita,Renewable Electricity Production
0,NaN,Afghanistan,Afghanistan,321,10,78.669280
1,NaN,Albania,Albania,102,35,100.000000
2,NaN,Algeria,Algeria,1959,51,0.551010
3,NaN,American Samoa,American Samoa,...,...,0.641026
4,NaN,Andorra,Andorra,9,121,88.695650

In [ ]:
Energy = Energy.drop(columns=['Unnamed: 0', 'Unnamed: 1'])

In [ ]:
Energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']

In [ ]:
Energy = Energy.replace("...", np.nan)

/tmp/ipykernel_1699/1019826293.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Energy = Energy.replace("...", np.nan)

In [ ]:
Energy["Energy Supply"] /= 1000000
Energy.head()

          Country  Energy Supply  Energy Supply per Capita  % Renewable
0     Afghanistan       0.000321                      10.0    78.669280
1         Albania       0.000102                      35.0   100.000000
2         Algeria       0.001959                      51.0     0.551010
3  American Samoa            NaN                       NaN     0.641026
4         Andorra       0.000009                     121.0    88.695650

In [ ]:
Energy['Country'] = (
    Energy['Country']
    .str.replace(r'\d+', '', regex=True)
    .str.replace(r' \(.*\)', '', regex=True)
    .replace({
        'Republic of Korea': 'South Korea',
        'United States of America': 'United States',
        'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
        'China, Hong Kong Special Administrative Region': 'Hong Kong'
    })
)

In [ ]:
Energy['Country'] = Energy['Country'].replace({
    'Bolivia (Plurinational State of)': 'Bolivia',
    'Switzerland17': 'Switzerland',
})

In [ ]:
try:
  GDP = pd.read_excel('/content/world_bank.xls', header = 3)
  print("Successfully loaded data")
except FileNotFoundError:
  print("File not found")
GDP.head()

Successfully loaded data

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.276188e+09,3.395794e+09,2.610039e+09,3.126019e+09,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.112502e+10,2.161623e+10,2.350628e+10,2.804836e+10,2.592067e+10,2.947210e+10,...,9.859871e+11,1.006526e+12,9.273485e+11,8.851764e+11,1.021043e+12,1.007196e+12,1.000834e+12,9.275933e+11,1.081998e+12,1.169484e+12
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,...,2.056449e+10,2.055058e+10,1.999814e+10,1.801955e+10,1.889635e+10,1.841886e+10,1.890450e+10,2.014345e+10,1.458314e+10,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.044764e+10,1.117321e+10,1.199053e+10,1.272769e+10,1.389811e+10,1.492979e+10,...,8.339481e+11,8.943225e+11,7.686447e+11,6.913634e+11,6.848988e+11,7.670257e+11,8.225384e+11,7.864600e+11,8.444597e+11,8.778633e+11
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.334016e+11,1.372444e+11,8.721930e+10,4.984049e+10,6.897277e+10,7.779294e+10,6.930911e+10,5.024137e+10,6.568544e+10,1.067136e+11

In [ ]:
GDP['Country Name'] = GDP['Country Name'].replace({
    'Korea, Rep.': 'South Korea',
    'Iran, Islamic Rep.': 'Iran',
    'Hong Kong SAR, China': 'Hong Kong'})

In [ ]:
ScimEn = pd.read_excel('/content/scimagojr country rank 1996-2024.xlsx')
ScimEn.head()

,Rank,Country,Region,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,1,China,Asiatic Region,472465,470142,6591474,4594673,13.95,380
1,2,United States,Northern America,222772,217929,4131736,1119917,18.55,491
2,3,India,Asiatic Region,96975,94714,1243636,479638,12.82,258
3,4,United Kingdom,Western Europe,61946,60287,1326766,207337,21.42,313
4,5,Japan,Asiatic Region,61939,61307,813472,166907,13.13,246

In [ ]:
ScimEn = ScimEn.head(15)
ScimEn = ScimEn.drop(columns = ['Region'])

In [ ]:
GDP = GDP.loc[:, ['Country Name'] + list(map(str, range(2006, 2016)))]
GDP = GDP.rename(columns = {'Country Name': 'Country'})

In [ ]:
answer_one = pd.merge(ScimEn, Energy, on='Country', how = 'left')
answer_one = pd.merge(answer_one, GDP, on='Country', how = 'left')
answer_one = answer_one.set_index('Country')

In [ ]:
answer_one.columns

Index(['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'],
      dtype='object')

In [ ]:
answer_one

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,472465,470142,6591474,4594673,13.95,380,0.127191,93.0,19.754910,2.752119e+12,3.550328e+12,4.594337e+12,5.101691e+12,6.087192e+12,7.551545e+12,8.532186e+12,9.570471e+12,1.047562e+13,1.106157e+13
United States,2,222772,217929,4131736,1119917,18.55,491,0.090838,286.0,11.570980,1.381559e+13,1.447423e+13,1.476986e+13,1.447806e+13,1.504896e+13,1.559973e+13,1.625397e+13,1.684319e+13,1.755068e+13,1.820602e+13
India,3,96975,94714,1243636,479638,12.82,258,0.033195,26.0,14.969080,9.402599e+11,1.216736e+12,1.198895e+12,1.341888e+12,1.675616e+12,1.823052e+12,1.827638e+12,1.856721e+12,2.039126e+12,2.103588e+12
United Kingdom,4,61946,60287,1326766,207337,21.42,313,0.007920,124.0,10.600470,2.709978e+12,3.092996e+12,2.931684e+12,2.417566e+12,2.491397e+12,2.666403e+12,2.706341e+12,2.786315e+12,3.065223e+12,2.934858e+12
Japan,5,61939,61307,813472,166907,13.13,246,0.018984,149.0,10.232820,4.601663e+12,4.579750e+12,5.106679e+12,5.289494e+12,5.759072e+12,6.233147e+12,6.272363e+12,5.212328e+12,4.896994e+12,4.444931e+12
Germany,6,55466,54296,932195,185376,16.81,274,0.013261,165.0,17.901530,2.994704e+12,3.425578e+12,3.745264e+12,3.411261e+12,3.399668e+12,3.749315e+12,3.527143e+12,3.733805e+12,3.889093e+12,3.357586e+12
Russian Federation,7,49938,49562,268391,112125,5.37,123,0.030709,214.0,17.288680,9.899321e+11,1.299703e+12,1.660848e+12,1.222646e+12,1.524917e+12,2.045923e+12,2.208294e+12,2.292470e+12,2.059242e+12,1.363482e+12
Canada,8,44877,44004,1082361,161133,24.12,305,0.010431,296.0,61.945430,1.319265e+12,1.468820e+12,1.552990e+12,1.374625e+12,1.617343e+12,1.793327e+12,1.828366e+12,1.846597e+12,1.805750e+12,1.556509e+12
Italy,9,42635,40695,767280,171442,18.00,227,0.006530,109.0,33.667230,1.949552e+12,2.213102e+12,2.408655e+12,2.199929e+12,2.136100e+12,2.294994e+12,2.086958e+12,2.141924e+12,2.162010e+12,1.836638e+12
South Korea,10,42534,42174,761076,124789,17.89,215,0.011007,221.0,2.279353,1.053217e+12,1.172614e+12,1.047339e+12,9.439419e+11,1.144067e+12,1.253223e+12,1.278428e+12,1.370795e+12,1.484318e+12,1.465773e+12
Iran,11,35889,35484,798505,211983,22.25,218,0.009172,119.0,5.707721,2.662989e+11,3.498816e+11,4.123362e+11,4.163970e+11,4.868076e+11,6.261331e+11,6.440355e+11,4.927756e+11,4.603828e+11,4.082129e+11
France,12,33407,32698,637552,99244,19.08,235,0.010597,166.0,17.020280,2.320536e+12,2.660591e+12,2.930304e+12,2.700887e+12,2.645188e+12,2.865158e+12,2.683672e+12,2.811877e+12,2.855964e+12,2.439189e+12
Spain,13,32521,31781,726414,118758,22.34,233,0.004923,106.0,37.968590,1.260399e+12,1.474003e+12,1.631863e+12,1.491473e+12,1.422108e+12,1.480710e+12,1.324751e+12,1.355580e+12,1.371821e+12,1.196157e+12
Australia,14,31047,30232,760284,99637,24.49,262,0.005386,231.0,11.810810,7.479074e+11,8.544273e+11,1.055686e+12,9.286298e+11,1.148570e+12,1.398456e+12,1.546953e+12,1.576330e+12,1.467590e+12,1.350580e+12
Brazil,15,30840,30383,371926,84223,12.06,167,0.012149,59.0,69.648030,1.107627e+12,1.397114e+12,1.695855e+12,1.666996e+12,2.208838e+12,2.616157e+12,2.465228e+12,2.472819e+12,2.456044e+12,1.802212e+12

###Question 2

In [ ]:
def answer_two():
    Top15 = answer_one
    years = [str(year) for year in range(2006, 2016)]
    avgGDP = Top15[years].mean(axis=1).sort_values(ascending=False)
    return avgGDP
print(answer_two())

Country
United States         1.570403e+13
China                 6.927707e+12
Japan                 5.239642e+12
Germany               3.523342e+12
United Kingdom        2.780276e+12
France                2.691337e+12
Italy                 2.142986e+12
Brazil                1.988889e+12
Russian Federation    1.666746e+12
Canada                1.616359e+12
India                 1.602352e+12
Spain                 1.400886e+12
South Korea           1.221372e+12
Australia             1.207513e+12
Iran                  4.563261e+11
dtype: float64

###Question 3

In [ ]:
def answer_three():
  avgGDP = answer_two()
  country = avgGDP.index[5]
  Top15 = answer_one
  answer = Top15.loc[country]['2015'] - Top15.loc[country]['2006']
  return answer
print(answer_three())

118652421857.7959

###Question 4

In [ ]:
def answer_four():
  Top15 = answer_one
  Top15["Self-Citations to Total Citations"] = Top15['Self-citations']/ Top15['Citations']
  country = Top15["Self-Citations to Total Citations"].idxmax()
  max_ratio = Top15.loc[country, "Self-Citations to Total Citations"]
  return (country, max_ratio)
print(answer_four())

('China', np.float64(0.6970630544852335))

###Question 5

In [ ]:
def answer_five():
    Top15 = answer_one
    Top15["Population"] = Top15["Energy Supply"] * 1000000/ Top15["Energy Supply per Capita"]
    third = Top15["Population"].nlargest(3).index[-1]
    return third
print(answer_five())

United States

###Question 6

In [ ]:
def answer_six():
    Top15 = answer_one
    Top15['Citable Documents Per Person'] = Top15['Citable documents'] / Top15['Population']
    return Top15['Citable Documents Per Person'].corr(Top15['Energy Supply per Capita'], method='pearson')
print(answer_six())

0.6905473831164102

###Question 7

In [ ]:
def answer_seven():
    Top15 = answer_one
    ContinentDict  = {
        'China':'Asia',
        'United States':'North America',
        'Japan':'Asia',
        'United Kingdom':'Europe',
        'Russian Federation':'Europe',
        'Canada':'North America',
        'Germany':'Europe',
        'India':'Asia',
        'France':'Europe',
        'South Korea':'Asia',
        'Italy':'Europe',
        'Spain':'Europe',
        'Iran':'Asia',
        'Australia':'Australia',
        'Brazil':'South America'}
    Top15['Continent'] = Top15.index.to_series().map(ContinentDict)
    result = Top15.groupby('Continent')['Population'].agg(
        size='count',
        sum='sum',
        mean='mean',
        std='std')
    return result
print(answer_seven())

               size          sum        mean         std
Continent
Asia              5  2898.666387  579.733277  679.097888
Australia         1    23.316017   23.316017         NaN
Europe            6   457.929667   76.321611   34.647667
North America     2   352.855249  176.427625  199.669645
South America     1   205.915254  205.915254         NaN